version: '3.8'

services:
  backend:
    build: .
    container_name: tssie_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Sobrescreve o REDIS_URL do .env pra refletir o host do banco que a stack cria
      - REDIS_URL=redis://redis:6379
    volumes:
      # Bind Mount para desenvolvimento (Hot Reloading ativo)
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    networks:
      - backend-net

  redis:
    image: redis:7-alpine
    container_name: tssie_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend-net

  # INFRAESTRUTURA EVOLUTION API
  evolution-db:
    image: postgres:15
    container_name: evolution-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${EVO_DB_USER}
      POSTGRES_PASSWORD: ${EVO_DB_PASSWORD}
      POSTGRES_DB: ${EVO_DB_NAME}
    ports:
      - "5433:5432" # Porta alternativa para DBeaver
    volumes:
      - evolution_db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  evolution-redis:
    image: redis:7-alpine
    container_name: evolution-redis
    restart: on-failure
    networks:
      - backend-net

  evolution-api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution-api
    restart: on-failure
    depends_on:
      - evolution-db
      - evolution-redis
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - API_KEY=${EVO_GLOBAL_API_KEY}
      - AUTHENTICATION_API_KEY=${EVO_AUTH_KEY}
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${EVO_DB_USER}:${EVO_DB_PASSWORD}@evolution-db:5432/${EVO_DB_NAME}?schema=public
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution-redis:6379
      - MANAGER_ENABLED=true
    # para desenvolviemnto
    ports:
      - "8080:8080"
    networks:
      - backend-net

volumes:
  redis_data:
  evolution_db_data:


networks:
  backend-net:
    driver: bridge
