version: '3.8'

services:
  backend:
    build: .
    container_name: tssie_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Sobrescreve o REDIS_URL do .env pra refletir o host do banco que a stack cria
      - REDIS_URL=redis://redis:6379
    volumes:
      # Bind Mount para desenvolvimento (Hot Reloading ativo)
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: tssie_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
